### ISSUE TITLE
Connecting to non-existing server doesn't fail until a request is made

### ISSUE THREAD

**Issue by WJWH** [informatikr/hedis#79]
If you try to connect to a redis instance that isn't running, the `connect` function does not complain. Only when you try to use the connection is an exception thrown (by the `connectTo` function from package `Network`). I really feel this should happen during the call to `connect`.

Easily reproducible in GHCI: (make sure redis-server is not running on your local machine)
`> import Database.Redis`
`> conn <- connect defaultConnectInfo --no problem so far`
`> runRedis conn ping --throws exception "*** Exception: connect: does not exist (Connection refused)"`

I'm not sure where the problem lies. At first I thought that laziness was the culprit, but since the usual tricks with seq didn't work for me I now suspect Data.Pool to be the culprit. I could easily be wrong though.

**Comment by k-bx** [comment]
@WJWH redis has a ping command to check end-to-end communication, so I suggest just doing that after you connect

**Comment by WJWH** [comment]
I'm aware of the ping command, in fact I even used it in the demo in my initial post :). While just pinging the server after connecting would solve my problem, this will likely bite a lot more people than just me in the long term. All these people would have to google the problem, hopefully find this issue and then add the ping command to their code. 

On the other hand it would be (slightly) wasteful to add a ping to the standard connecting call. Why does the `connectTo` call throw its exception so late?

**Comment by k-bx** [comment]
@WJWH because it doesn't do any network operations, it just creates a pool which creates or reuses connections on demand. As you mentioned, doing some network-related work like sending ping on each `connectTo` is a too big of an overhead. I just checked a Python driver, it doesn't do any work and doesn't raise an exception when you create a `StrictRedis` instance as well, so I guess we're on par here.

I agree this might be a common issue, so I'd be happy to accept a PR which would mention this in `connectTo`'s haddock and add a `connectToAndPing` function right after the `connectTo`, I think it'd resolve this issue. What do you think?

**Comment by WJWH** [comment]
I agree with your suggestions and I'll write a PR tomorrow. I think the `connectToAndPing` should be called `strictConnect` though, because this describes its use better. The exact details it's internal operation are not really important to someone reading code where function is used. I'll mention how it works in the haddock of course.

**Comment by k-bx** [comment]
@WJWH `strictConnect` is too vague in my opinion, it's similar to the idea of using "smart" in your names, which is a bad practice usually. It's not clear what's more strict about `strictConnect` out of its name, while out of `connectToAndPing` it's obvious what it does (well, connects and pings). So, I would really like to not go into the "strict" prefix.

Also, please use that function in hedis's tutorial code, so that users see it by default. Thanks!

**Comment by qrilka** [comment]
I'm not sure if it will sound better but I propose another name - `checkedConnect`. Your variant @k-bx is more explicit though...

**Comment by k-bx** [comment]
checkedConnect looks good to me (while I'd still stick to AndPing)

**Comment by WJWH** [comment]
It originally tripped over a warning where I forgot to add a void call. Anyway, I implemented the `checkedConnect` function with a call to `ping` after connecting, updated the haddocks and added some text to the tutorial section in Redis.hs. I had to move the `ping` function to Core.hs for this, but I altered the codegen utilities to match this. It now works as expected.

**Comment by k-bx** [comment]
@WJWH thanks and sorry for a late merge! Released under 0.9.4 version.
