### ISSUE TITLE
Cannot install Hedis on Windows

### ISSUE THREAD

**Issue by rwobben** [informatikr/hedis#95]
Hello, 

When I try to install hedis on Windows 10 I see the build failing with this message : 

Not in scope: data constructor `UnixSocket'
Perhaps you meant variable `NS.bindSocket' (imported from Network.Socket)

Roelof

**Comment by k-bx** [comment]
Oops, might be related to the recent changes from @erickg and @alcidesv. @erickg would you be able to look at this please? (if not, I'd understand)

**Comment by erickg** [comment]
Windows? people use that really? :-P

I think this was probably a problem with the fix from @alcidesv .. since the later fix (which was merged yesterday) doesn't use the `UnixSocket` constructor anymore, I will guess that the latest version after the merge doesn't have this problem? @rwobben can you please double check using the latest available version?

Cheers

**Comment by rwobben** [comment]
I use stack and I use version 0.9.10 so not the newest version. 
So i have to check if the newest version of stack has which version of hedis

**Comment by erickg** [comment]
Just add:

```
extra-deps: [hedis-0.9.11]
```

to your stack.yaml and you should be good to go.

Cheers

**Comment by rwobben** [comment]
Thanks, now everything is working fine
